import React, { useState, useEffect } from 'react'
import { motion } from 'framer-motion'
import axios from 'axios'

const ProgressSaver = ({ sessionData, onUpdate, onPrev }) => {
  const [professorGuidance, setProfessorGuidance] = useState(null)
  const [isLoading, setIsLoading] = useState(false)
  const [isSaving, setIsSaving] = useState(false)
  const [saveMessage, setSaveMessage] = useState('')

  useEffect(() => {
    if (sessionData?.selected_topic && !professorGuidance) {
      generateProfessorGuidance()
    }
  }, [sessionData])

  const generateProfessorGuidance = async () => {
    if (!sessionData?.selected_topic) return

    setIsLoading(true)
    
    try {
      const response = await axios.post('/professor-guidance', {
        topic: sessionData.selected_topic
      })
      setProfessorGuidance(response.data.guidance)
    } catch (error) {
      console.error('Error generating professor guidance:', error)
    } finally {
      setIsLoading(false)
    }
  }

  const handleSaveProgress = async () => {
    setIsSaving(true)
    setSaveMessage('')
    
    try {
      await onUpdate({ is_completed: true })
      setSaveMessage('Your research journey has been saved successfully!')
    } catch (error) {
      console.error('Error saving progress:', error)
      setSaveMessage('Error saving progress. Please try again.')
    } finally {
      setIsSaving(false)
    }
  }

  const downloadProposal = () => {
    const proposalText = `
RESEARCH PROPOSAL

Title: ${sessionData?.proposal_title || 'Your Research Title'}

Abstract:
${sessionData?.proposal_abstract || 'Your research abstract'}

Research Objectives:
${sessionData?.proposal_objectives || 'Your research objectives'}

Methodology:
${sessionData?.proposal_methodology || 'Your research methodology'}

Generated by AI Research Journey Platform
Date: ${new Date().toLocaleDateString()}
    `.trim()

    const blob = new Blob([proposalText], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `research_proposal_${sessionData?.student_name || 'student'}_${new Date().toISOString().split('T')[0]}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <div className="max-w-4xl mx-auto">
      <div className="card">
        <div className="text-center mb-8">
          <h2 className="text-3xl font-bold text-gray-900 mb-4">Save Your Progress</h2>
          <p className="text-gray-600">
            Congratulations! You've completed your research journey. Here's a summary of your work:
          </p>
        </div>

        {/* Progress Summary */}
        <div className="bg-green-50 border border-green-200 rounded-lg p-6 mb-8">
          <h3 className="text-lg font-semibold text-green-900 mb-4">✅ Research Journey Complete</h3>
          <div className="grid md:grid-cols-2 gap-4 text-sm">
            <div>
              <p><strong>Student:</strong> {sessionData?.student_name}</p>
              <p><strong>Area of Interest:</strong> {sessionData?.area_of_interest}</p>
              <p><strong>Selected Topic:</strong> {sessionData?.selected_topic}</p>
            </div>
            <div>
              <p><strong>Literature Review:</strong> ✅ Completed</p>
              <p><strong>Research Proposal:</strong> ✅ Generated</p>
              <p><strong>Session ID:</strong> {sessionData?.id}</p>
            </div>
          </div>
        </div>

        {/* Professor Contact Guidance */}
        {isLoading ? (
          <div className="text-center py-4">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary-600 mx-auto mb-2"></div>
            <p className="text-gray-600">Loading professor contact guidance...</p>
          </div>
        ) : professorGuidance && (
          <div className="mb-8">
            <h3 className="text-xl font-semibold text-gray-900 mb-4">📧 Professor Contact Guidance</h3>
            <div className="bg-blue-50 border border-blue-200 rounded-lg p-6">
              <div className="prose max-w-none">
                <div className="whitespace-pre-wrap text-gray-700 leading-relaxed">
                  {professorGuidance.guidance}
                </div>
              </div>
            </div>

            {professorGuidance.sample_email && (
              <div className="mt-6">
                <h4 className="text-lg font-semibold text-gray-900 mb-3">Sample Email Template</h4>
                <div className="bg-gray-50 border border-gray-200 rounded-lg p-4">
                  <pre className="text-sm text-gray-700 whitespace-pre-wrap">
                    {professorGuidance.sample_email}
                  </pre>
                </div>
              </div>
            )}
          </div>
        )}

        {/* Action Buttons */}
        <div className="space-y-4">
          <div className="flex flex-wrap gap-4">
            <button
              onClick={downloadProposal}
              className="btn-primary flex items-center"
            >
              <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
              Download Proposal
            </button>

            <button
              onClick={handleSaveProgress}
              disabled={isSaving}
              className="btn-secondary flex items-center disabled:opacity-50"
            >
              <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7H5a2 2 0 00-2 2v9a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-3m-1 4l-3-3m0 0l-3 3m3-3v12" />
              </svg>
              {isSaving ? 'Saving...' : 'Save Progress'}
            </button>
          </div>

          {saveMessage && (
            <motion.div
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              className={`p-4 rounded-lg ${
                saveMessage.includes('Error') 
                  ? 'bg-red-50 border border-red-200 text-red-700'
                  : 'bg-green-50 border border-green-200 text-green-700'
              }`}
            >
              {saveMessage}
            </motion.div>
          )}
        </div>

        {/* Next Steps */}
        <div className="mt-8 bg-yellow-50 border border-yellow-200 rounded-lg p-6">
          <h3 className="text-lg font-semibold text-yellow-900 mb-3">🚀 Next Steps</h3>
          <div className="text-yellow-800 space-y-2">
            <p>1. <strong>Contact Professors:</strong> Use the guidance above to reach out to potential advisors</p>
            <p>2. <strong>Refine Your Proposal:</strong> Incorporate feedback from professors and mentors</p>
            <p>3. <strong>Start Literature Review:</strong> Begin reading the key papers identified</p>
            <p>4. <strong>Develop Research Plan:</strong> Create a detailed timeline for your research</p>
            <p>5. <strong>Apply for Funding:</strong> Look for research grants and scholarships</p>
          </div>
        </div>

        <div className="flex justify-between mt-8">
          <button onClick={onPrev} className="btn-secondary">
            Back to Proposal
          </button>
          <div className="text-sm text-gray-500">
            Your research journey is complete! 🎉
          </div>
        </div>
      </div>
    </div>
  )
}

export default ProgressSaver


